/**
 * Markdown Reporter
 * Formats analysis results for PR comments and documentation
 */

import { FullReport, Finding, Savings } from '../types.js';

export class MarkdownReporter {
  format(report: FullReport): string {
    const lines: string[] = [];

    // Header
    lines.push('# Dev Optimizer Report');
    lines.push('');
    lines.push(`**Analyzed:** ${report.path}`);
    lines.push(`**Timestamp:** ${report.timestamp}`);
    lines.push(`**Score:** ${report.score}/100`);
    lines.push('');

    // Baseline
    lines.push('## 📊 Baseline');
    lines.push('');
    lines.push('| Metric | Value |');
    lines.push('|--------|-------|');
    lines.push(`| Project Type | ${report.baseline.projectType || 'Unknown'} |`);
    lines.push(`| Dependencies | ${report.baseline.dependencyCount} |`);
    lines.push(`| Docker | ${report.baseline.hasDockerfile ? '✅' : '❌'} |`);
    lines.push(`| CI/CD | ${report.baseline.hasCi ? '✅' : '❌'} |`);
    lines.push('');

    // Top Findings
    if (report.topFindings.length > 0) {
      lines.push('## 🔴 Top Findings');
      lines.push('');
      
      for (const finding of report.topFindings.slice(0, 5)) {
        lines.push(this.formatFinding(finding));
      }
    }

    // Quick Wins
    if (report.quickWins.length > 0) {
      lines.push('## 💡 Quick Wins (Auto-fixable)');
      lines.push('');
      
      for (const finding of report.quickWins) {
        lines.push(`- [${finding.severity.toUpperCase()}] **${finding.title}**`);
        lines.push(`  - Impact: ${finding.impact.estimate}`);
        lines.push(`  - Fix: ${finding.suggestedFix.description}`);
      }
      lines.push('');
    }

    // Manual Review
    if (report.manualReview.length > 0) {
      lines.push('## ⚠️ Requires Manual Review');
      lines.push('');
      
      for (const finding of report.manualReview) {
        lines.push(`- [${finding.severity.toUpperCase()}] **${finding.title}** — ${finding.description}`);
      }
      lines.push('');
    }

    // All Findings by Domain
    lines.push('## 📋 All Findings');
    lines.push('');

    const dockerFindings = report.findings.filter(f => f.domain === 'docker');
    const ciFindings = report.findings.filter(f => f.domain === 'ci');
    const depsFindings = report.findings.filter(f => f.domain === 'deps');

    if (dockerFindings.length > 0) {
      lines.push('### 🐳 Docker');
      lines.push('');
      lines.push(this.formatFindingsTable(dockerFindings));
    }

    if (ciFindings.length > 0) {
      lines.push('### 🔄 CI/CD');
      lines.push('');
      lines.push(this.formatFindingsTable(ciFindings));
    }

    if (depsFindings.length > 0) {
      lines.push('### 📦 Dependencies');
      lines.push('');
      lines.push(this.formatFindingsTable(depsFindings));
    }

    // Savings
    lines.push('## 💰 Potential Savings');
    lines.push('');
    lines.push('| Metric | Value |');
    lines.push('|--------|-------|');
    
    if (report.totalSavings.sizeMB > 0) {
      lines.push(`| Size | ${report.totalSavings.sizeMB} MB |`);
    }
    if (report.totalSavings.timeSeconds > 0) {
      lines.push(`| Time | ${Math.round(report.totalSavings.timeSeconds / 60)} min/CI run |`);
    }
    if (report.totalSavings.monthlyCostEstimate) {
      lines.push(`| Monthly Cost | ~$${report.totalSavings.monthlyCostEstimate} |`);
    }
    if (report.totalSavings.percentImprovement > 0) {
      lines.push(`| Improvement | ${report.totalSavings.percentImprovement}% |`);
    }
    lines.push('');

    // Footer
    lines.push('---');
    lines.push('');
    lines.push(`Generated by [Dev Optimizer](https://github.com/bigcheburashka/dev-optimizer) v${report.version}`);

    return lines.join('\n');
  }

  private formatFinding(finding: Finding): string {
    const lines: string[] = [];
    
    const severityEmoji = {
      critical: '🔴',
      high: '🟠',
      medium: '🟡',
      low: '🟢'
    };

    lines.push(`### ${severityEmoji[finding.severity]} ${finding.title}`);
    lines.push('');
    lines.push(finding.description);
    lines.push('');
    
    if (finding.evidence.file) {
      lines.push(`**File:** \`${finding.evidence.file}\``);
    }
    
    lines.push(`**Impact:** ${finding.impact.estimate}`);
    lines.push('');
    
    if (finding.suggestedFix.autoFixable) {
      lines.push(`**Fix:** ${finding.suggestedFix.description} (auto-fixable ✅)`);
    } else {
      lines.push(`**Suggestion:** ${finding.suggestedFix.description}`);
    }
    lines.push('');

    return lines.join('\n');
  }

  private formatFindingsTable(findings: Finding[]): string {
    const lines: string[] = [];
    
    lines.push('| Severity | Finding | Impact | Auto-fix |');
    lines.push('|----------|---------|--------|----------|');
    
    for (const finding of findings) {
      const autoFix = finding.suggestedFix.autoFixable ? '✅' : '❌';
      lines.push(`| ${finding.severity.toUpperCase()} | ${finding.title} | ${finding.impact.estimate} | ${autoFix} |`);
    }
    lines.push('');

    return lines.join('\n');
  }

  getExtension(): string {
    return '.md';
  }
}